#!/usr/bin/env bash
#Script that prints a story of every user in passwd whit while and read command
while IFS=":" read {a..g} ; do echo The user $a is part of the $d gang, lives in $f and rides $g. $c's place is protected by the passcode $b, more info about the user here: $e; done < file
