#!/usr/bin/env bash
#Script that gives information about a file
FILENAME="./school" 
if [[-e $FILENAME ]]
then
    echo "school file exist"
    if [ -s $FILENAME ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f $FILENAME ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi 

