#!/usr/bin/env bash
#Script that print "To infinity and beyond"
# shellcheck disable=SC200
touch /var/run/myscript.pid
cat $BASHPID > /var/run/myscript.pid 
trap "rm /var/run/myscript.pid; echo I hate the kill command ; exit" TERM 
trap 'echo Y U no love me?' INT 
#trap 'rm /var/run/myscript.pid; exit' QUIT 
for ((;;))
do
    echo "To infinity and beyond"
    sleep 2
done
