#!/usr/bin/env bash
#Script that print "To infinity and beyond"
# shellcheck disable=SC200
touch /var/run/myscript.pid | echo $BASHPID > /var/run/myscript.pid 
#for ((;;))
#do
#    echo "To infinity and beyond"
#    sleep 2
#done
