#!/usr/bin/env bash
#Script that print "To infinity and beyond"
# shellcheck disable=SC200

case "$1" in
    "start")
        #touch /var/run/my_process.pid
        echo $BASHPID > /var/run/my_process.pid
        echo "manage_my_process started"
        ./manage_my_process &
        ;;
    "stop")
        kill -9 "$(pgrep -f "./manage_my_process")"
        rm -r "/var/run/my_process.pid"
        echo "manage_my_process stopped"
        ;;
    "restart")
        kill -9 "$(pgrep -f "./manage_my_process")"
        rm -r "/var/run/my_process.pid" 
        ./manage_my_process &
        echo $BASHPID > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    "")
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
